import {
  CartIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  ComputerIcon,
  CrissCrossIcon,
  CrossedUserIcon,
  CupIcon,
  DiscordLogoIcon,
  DrillIcon,
  DroneIcon,
  EyeIcon,
  FAQIcon,
  FacebookLogoIcon,
  FlaskIcon,
  FunnelIcon,
  GamepadIcon,
  GoogleIcon,
  HairdryerIcon,
  HeadphonesMicIcon,
  HeartIcon,
  HideEyeIcon,
  HouseIcon,
  InfoIcon,
  InstagramLogoIcon,
  LanguagesIcon,
  LaptopIcon,
  LeftArrowIcon,
  ListIcon,
  LogoutIcon,
  MagnifyingGlassIcon,
  MenuAltIcon,
  MicrophoneIcon,
  MonitorIcon,
  RedditLogoIcon,
  RightArrowIcon,
  SmartphoneIcon,
  SpeakerIcon,
  TagIcon,
  TiktokLogoIcon,
  UserIcon,
  WashingMachineIcon,
  XLogoItem,
  YoutubeLogoIcon,
} from '@/app/components/ui-kit/icons/icons';

export const icons = {
  laptop: LaptopIcon,
  computer: ComputerIcon,
  smartphone: SmartphoneIcon,
  gamepad: GamepadIcon,
  monitor: MonitorIcon,
  speaker: SpeakerIcon,
  washingMachine: WashingMachineIcon,
  hairdryer: HairdryerIcon,
  drill: DrillIcon,
  drone: DroneIcon,
  flask: FlaskIcon,
  cup: CupIcon,
  tag: TagIcon,
  magnifyingGlass: MagnifyingGlassIcon,
  menuAlt: MenuAltIcon,
  microphone: MicrophoneIcon,
  info: InfoIcon,
  facebook: FacebookLogoIcon,
  instagram: InstagramLogoIcon,
  youtube: YoutubeLogoIcon,
  tiktok: TiktokLogoIcon,
  discord: DiscordLogoIcon,
  reddit: RedditLogoIcon,
  x: XLogoItem,
  heart: HeartIcon,
  rightArrow: RightArrowIcon,
  leftArrow: LeftArrowIcon,
  chevronDown: ChevronDownIcon,
  chevronUp: ChevronUpIcon,
  cart: CartIcon,
  user: UserIcon,
  crossedUser: CrossedUserIcon,
  crissCross: CrissCrossIcon,
  eye: EyeIcon,
  hideEye: HideEyeIcon,
  languages: LanguagesIcon,
  faq: FAQIcon,
  list: ListIcon,
  headphonesMic: HeadphonesMicIcon,
  check: CheckIcon,
  google: GoogleIcon,
  logout: LogoutIcon,
  house: HouseIcon,
  funnel: FunnelIcon,
};

export type IconName = keyof typeof icons;
